services:
  localai:
    extends:
      file: docker-compose.yaml
      service: localai
    environment:
      - LOCALAI_SINGLE_ACTIVE_BACKEND=true
      - DEBUG=true
    image: localai/localai:master-cublas-cuda12-ffmpeg-core
    # For images with python backends, use:
    # image: localai/localai:master-cublas-cuda12-ffmpeg
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  mcpbox:
    extends:
      file: docker-compose.yaml
      service: mcpbox

  localrecall:
    extends:
      file: docker-compose.yaml
      service: localrecall

  localrecall-healthcheck:
    extends:
      file: docker-compose.yaml
      service: localrecall-healthcheck

  localagi:
    extends:
      file: docker-compose.yaml
      service: localagi
